class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?

    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do
  # Routes for course_bundles generated by controller generator
  resources :course_bundles, only: [:index, :show] do
    member do
      post :purchase
    end
  end
  # End routes for course_bundles

  # Routes for products generated by controller generator
  resources :products, only: [:index]
  # End routes for products

  # Routes for offline_bookings generated by controller generator
  resources :offline_bookings, only: [:index]
  # End routes for offline_bookings

  # PWA routes
  get '/manifest.json', to: 'pwa#manifest', defaults: { format: :json }
  get '/service-worker.js', to: 'pwa#service_worker', defaults: { format: :js }
  # Routes for offline_bookings generated by controller generator
  resources :offline_bookings, only: [:index, :new, :create, :destroy]
  # End routes for offline_bookings

  # Routes for subscriptions generated by controller generator
  resources :subscriptions, only: [:new, :create, :destroy]
  # End routes for subscriptions

  resources :payments, only: [:index] do
    member do
      get :pay
      post :pay
      get :success
      get :failure
    end
  end
  post '/webhooks/stripe', to: 'payments#webhook'
  # Routes for progresses generated by controller generator
  resources :progresses do
    get :dashboard, on: :collection
  end
  # End routes for progresses

  # Routes for lessons generated by controller generator
  resources :lessons, only: [:show] do
    member do
      post :submit_homework
    end
  end
  # End routes for lessons

  # Routes for courses generated by controller generator
  resources :courses, only: [:index, :show] do
    member do
      post :purchase
    end
  end
  # End routes for courses

  # Authentication routes generated by authentication generator
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete 'sign_out', to: 'sessions#destroy', as: :sign_out
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resource :session, only: [:new, :show, :destroy] do
    get :devices, on: :member
    delete :destroy_one, on: :member
  end
  resources :registrations, only: [:new, :create]
  resource  :password, only: [:edit, :update]

  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  get  "/auth/failure",            to: "sessions/omniauth#failure"
  get  "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "/auth/:provider/callback", to: "sessions/omniauth#create"

  resource :invitation, only: [:new, :create]

  # Profile routes
  resource :profile, only: [:show, :edit, :update], controller: 'profiles' do
    member do
      get :edit_password
      patch :update_password
    end
  end

  # Authentication routes generated end

  # write your business logic routes here

  # API routes
  namespace :api do
    namespace :v1 do
      # API authentication routes
      post 'login', to: 'sessions#login'
      delete 'logout', to: 'sessions#destroy'
      post 'sign_up', to: 'registrations#create'
      resource :profile, only: [:show, :update], controller: 'profiles'
      put 'password', to: 'profiles#update_password'

      get 'health', to: 'health#index'
    end
  end

  root 'home#index'

  # Do not write business logic at admin dashboard
  namespace :admin do
    resources :course_bundles
    resources :products do
      member do
        post :refresh_og_image
      end
    end
    resources :courses
    resources :offline_bookings do
      member do
        post :mark_no_show
      end
    end
    resources :offline_schedules
    resources :payments, only: [:index, :show]
    resources :homeworks, only: [:index, :show, :destroy] do
      member do
        post :like
      end
    end
    resources :users, only: [:index, :show]
    resources :admin_oplogs, only: [:index, :show]
    resources :administrators
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    # Mount GoodJob dashboard
    mount GoodJob::Engine => 'good_job', :constraints => AdminConstraint.new

    root to: 'dashboard#index'
  end

  mount ActionCable.server => '/cable'

  # Catch-all route for all 404 errors - MUST be last
  match '*path', to: 'application#handle_routing_error', via: :all,
    constraints: lambda { |request|
      !request.path.start_with?('/rails/active_storage', '/assets', '/dev-assets')
    }
end
